### ISSUE TITLE
Installation of ingress plugin isn't described in the doc

### ISSUE THREAD

**Issue by avarabyeu** [reportportal/k8s#11]
Some comments regarding existing README guide:
1. Installation of ingress plugin isn't described:
```sh
minikube addons enable ingress
```

2. Minikube creation details:
```sh
minikube --memory 4096 --cpus 4 --vm-driver hyperkit
```

3. How to find minikube IP (some static one is present in the docs):
```sh
minikube ip
```

**Comment by encyclopod** [comment]
Updated.
