### ISSUE TITLE
Chart dependencies are broken as of June 2

### ISSUE THREAD

**Issue by dmckernanacv** [reportportal/k8s#264]
3 of Report Portal's chart dependencies come from Bitnami, and [recently they implemented a change](https://github.com/bitnami/charts/issues/10539) to their index which removes versions older than 6 months to reduce its size.

Report Portal is using dependencies far older than 6 months, and in its current state, the chart fails to install.

The `reportportal/requirements.yaml` should be updated to use the Bitnami workaround for their full index:

```diff
dependencies:
  - name: postgresql
    version: 10.9.4
-   repository: https://charts.bitnami.com/bitnami
+   repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    condition: postgresql.installdep.enable

  - name: rabbitmq
    version: 7.5.6
-   repository: https://charts.bitnami.com/bitnami
+   repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    condition: rabbitmq.installdep.enable

  - name: elasticsearch
    version: 7.10.2
    repository: https://helm.elastic.co
    condition: elasticsearch.installdep.enable

  - name: minio
    version: 7.1.9
-   repository: https://charts.bitnami.com/bitnami
+   repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    condition: minio.installdep.enable
```

**Comment by HardNorth** [comment]
@dmckernanacv I patched our `index.yaml` file in corresponding branch, it should be applied already.
