### ISSUE TITLE
Wrong job name

### ISSUE THREAD

**Issue by maluyvova** [reportportal/k8s#335]
---

### Description

I encountered an issue while deploying using the latest master branch from the repository and installing it via Helm. The problem arises with the initialization container in the UAT pod, preventing it from starting correctly.

### Issue Details

Pod: `release1-reportportal-uat-68c6d75c97-jq86q`
- Status: `Init:CrashLoopBackOff` (0/1)
- Events:
  - `Normal Started`: Container `migrations-waiting-init` started 5 times over 14 minutes.
  - `Warning BackOff`: Back-off restarting failed container `migrations-waiting-init` 47 times over 14 minutes.

### Logs Investigation

When checking the logs of the `migrations-waiting-init` container, I received an error:
```bash
kubectl logs release1-reportportal-uat-68c6d75c97-jq86q -c migrations-waiting-init
Error from server (NotFound): jobs.batch "release1-migrations" not found
```

However, upon inspecting the existing jobs:
```bash
kubectl get job
NAME                               COMPLETIONS   DURATION   AGE
release1-reportportal-migrations   1/1           2m16s      15m
```

### Helm Deployment

The Helm deployment was initiated with the following command:
```bash
helm install release1 --set uat.superadminInitPasswd.password="MyPassword" .
```

### Steps to Reproduce

1. Clone the repository.
2. Checkout the latest master branch.
3. Install the deployment using Helm.

### Expected Behavior

The UAT pod should initialize successfully without encountering the `NotFound` error related to the job.

### Additional Information

- Kubernetes version:1.28
- Helm version: version.BuildInfo{Version:"v3.12.2", GitCommit:"1e210a2c8cc5117d1055bfaa5d40f51bbc2e345e", GitTreeState:"clean", GoVersion:"go1.20.5"}

### Suggestions or Questions

- Any insights or suggestions on troubleshooting this issue?
- Are there any specific configurations that might have caused this discrepancy between the expected job name and the one reported in the error?

---

**Comment by raikbitters** [comment]
Hello @maluyvova. We've already resolved the issue in the development branch.
