### ISSUE TITLE
mongoDB

### ISSUE THREAD

**Issue by gogovan-vincentngai** [reportportal/k8s#7]
I think the correct of mongodb repo is mongo ?
https://hub.docker.com/_/mongo/

> mongodb:
>   repository: mongodb
>   tag: latest
>   pullPolicy: IfNotPresent

**Comment by DzmitryHumianiuk** [comment]
@encyclopod could you plz verify?

**Comment by encyclopod** [comment]
I fixed that.

**Comment by avarabyeu** [comment]
https://hub.docker.com/_/mongo/ is official repository
Version should be set to 3.4

**Comment by avarabyeu** [comment]
Current repo and version are correct
